version: "3.9"

services:
  zanaka-ui:
    image: ${IMAGE_TAG}
    container_name: zanaka_ui_prod
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3004:3000"
    environment:
      NODE_ENV: production
      BASE_BACKEND_URL: https://api.stmarysacademy.sc.ke/api/v1
      BACKEND_API_KEY: ${BACKEND_API_KEY}
      ENCRYPT_TO_BACKEND: 0
      BACKEND_PUBLIC_KEY: ${BACKEND_PUBLIC_KEY}
      BACKEND_PRIVATE_KEY: ${BACKEND_PRIVATE_KEY}
    restart: unless-stopped
